/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.2 */

#include "job.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(si_job_MemoryRegion, si_job_MemoryRegion, AUTO)


PB_BIND(si_job_FlashAlgorithm, si_job_FlashAlgorithm, AUTO)


PB_BIND(si_job_CortexM, si_job_CortexM, AUTO)


PB_BIND(si_job_Esp32Image, si_job_Esp32Image, AUTO)


PB_BIND(si_job_Esp32, si_job_Esp32, 2)


PB_BIND(si_job_SelfTest, si_job_SelfTest, AUTO)


PB_BIND(si_job_Target, si_job_Target, 2)


PB_BIND(si_job_Empty, si_job_Empty, AUTO)


PB_BIND(si_job_Read32, si_job_Read32, AUTO)


PB_BIND(si_job_Write32, si_job_Write32, AUTO)


PB_BIND(si_job_ReadModWrite32, si_job_ReadModWrite32, AUTO)


PB_BIND(si_job_Poll32, si_job_Poll32, AUTO)


PB_BIND(si_job_Delay, si_job_Delay, AUTO)


PB_BIND(si_job_Step, si_job_Step, AUTO)


PB_BIND(si_job_Procedure, si_job_Procedure, 2)


PB_BIND(si_job_Job, si_job_Job, 2)









