/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_SI_MANAGE_MANAGE_PB_H_INCLUDED
#define PB_SI_MANAGE_MANAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _si_manage_Trigger {
    si_manage_Trigger_TRIGGER_MANUAL = 0, /* Runs only on JOB_RUN_ONCE. */
    si_manage_Trigger_TRIGGER_AUTO_ON_DETECT = 1 /* Also runs whenever a target is plugged in. */
} si_manage_Trigger;

typedef enum _si_manage_RunState {
    si_manage_RunState_RUN_STATE_IDLE = 0,
    si_manage_RunState_RUN_STATE_RUNNING = 1
} si_manage_RunState;

typedef enum _si_manage_Outcome {
    si_manage_Outcome_OUTCOME_NONE = 0,
    si_manage_Outcome_OUTCOME_PASS = 1,
    si_manage_Outcome_OUTCOME_FAIL = 2,
    si_manage_Outcome_OUTCOME_CANCELLED = 3
} si_manage_Outcome;

/* Programming stage where a run failed or was cancelled. */
typedef enum _si_manage_Stage {
    si_manage_Stage_STAGE_NONE = 0,
    si_manage_Stage_STAGE_LOAD = 1,
    si_manage_Stage_STAGE_PRE_PROGRAM = 2,
    si_manage_Stage_STAGE_DETECT = 3,
    si_manage_Stage_STAGE_ERASE = 4,
    si_manage_Stage_STAGE_PROGRAM = 5,
    si_manage_Stage_STAGE_VERIFY = 6,
    si_manage_Stage_STAGE_SELF_TEST = 7,
    si_manage_Stage_STAGE_POST_PROGRAM = 8,
    si_manage_Stage_STAGE_CURRENT_TEST = 9
} si_manage_Stage;

/* Struct definitions */
typedef struct _si_manage_DeviceInfo {
    char serial[32];
    char firmware_version[32];
    uint32_t storage_total_kb;
    uint32_t storage_free_kb;
} si_manage_DeviceInfo;

/* Asset names are bare file names stored under /data on the device. */
typedef struct _si_manage_AssetBeginRequest {
    char name[32];
    uint32_t size;
    pb_byte_t sha256[32];
} si_manage_AssetBeginRequest;

typedef struct _si_manage_AssetBeginResponse {
    /* True when the device already holds this exact asset; nothing to upload. */
    bool present;
    /* Next byte to send. Non-zero when an interrupted upload is resumed. */
    uint32_t offset;
} si_manage_AssetBeginResponse;

/* Activates the job uploaded as asset "job.pb.new". Setting the active
 job's hash again only updates the trigger. */
typedef struct _si_manage_JobSetRequest {
    pb_byte_t sha256[32];
    si_manage_Trigger trigger;
} si_manage_JobSetRequest;

typedef struct _si_manage_RunResult {
    uint32_t run_id;
    si_manage_Outcome outcome;
    si_manage_Stage failed_stage;
    uint32_t duration_ms;
} si_manage_RunResult;

typedef struct _si_manage_JobStatus {
    bool has_job;
    char name[32];
    pb_byte_t sha256[32];
    si_manage_Trigger trigger;
    si_manage_RunState state;
    uint32_t current_run_id; /* Valid while RUNNING. */
    bool has_last_result;
    si_manage_RunResult last_result; /* run_id 0: nothing has run since boot. */
} si_manage_JobStatus;

typedef struct _si_manage_JobRunOnceResponse {
    uint32_t run_id;
} si_manage_JobRunOnceResponse;

typedef struct _si_manage_JobCancelRequest {
    uint32_t run_id; /* 0 cancels whatever is running. */
} si_manage_JobCancelRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _si_manage_Trigger_MIN si_manage_Trigger_TRIGGER_MANUAL
#define _si_manage_Trigger_MAX si_manage_Trigger_TRIGGER_AUTO_ON_DETECT
#define _si_manage_Trigger_ARRAYSIZE ((si_manage_Trigger)(si_manage_Trigger_TRIGGER_AUTO_ON_DETECT+1))

#define _si_manage_RunState_MIN si_manage_RunState_RUN_STATE_IDLE
#define _si_manage_RunState_MAX si_manage_RunState_RUN_STATE_RUNNING
#define _si_manage_RunState_ARRAYSIZE ((si_manage_RunState)(si_manage_RunState_RUN_STATE_RUNNING+1))

#define _si_manage_Outcome_MIN si_manage_Outcome_OUTCOME_NONE
#define _si_manage_Outcome_MAX si_manage_Outcome_OUTCOME_CANCELLED
#define _si_manage_Outcome_ARRAYSIZE ((si_manage_Outcome)(si_manage_Outcome_OUTCOME_CANCELLED+1))

#define _si_manage_Stage_MIN si_manage_Stage_STAGE_NONE
#define _si_manage_Stage_MAX si_manage_Stage_STAGE_CURRENT_TEST
#define _si_manage_Stage_ARRAYSIZE ((si_manage_Stage)(si_manage_Stage_STAGE_CURRENT_TEST+1))




#define si_manage_JobSetRequest_trigger_ENUMTYPE si_manage_Trigger

#define si_manage_RunResult_outcome_ENUMTYPE si_manage_Outcome
#define si_manage_RunResult_failed_stage_ENUMTYPE si_manage_Stage

#define si_manage_JobStatus_trigger_ENUMTYPE si_manage_Trigger
#define si_manage_JobStatus_state_ENUMTYPE si_manage_RunState




/* Initializer values for message structs */
#define si_manage_DeviceInfo_init_default        {"", "", 0, 0}
#define si_manage_AssetBeginRequest_init_default {"", 0, {0}}
#define si_manage_AssetBeginResponse_init_default {0, 0}
#define si_manage_JobSetRequest_init_default     {{0}, _si_manage_Trigger_MIN}
#define si_manage_RunResult_init_default         {0, _si_manage_Outcome_MIN, _si_manage_Stage_MIN, 0}
#define si_manage_JobStatus_init_default         {0, "", {0}, _si_manage_Trigger_MIN, _si_manage_RunState_MIN, 0, false, si_manage_RunResult_init_default}
#define si_manage_JobRunOnceResponse_init_default {0}
#define si_manage_JobCancelRequest_init_default  {0}
#define si_manage_DeviceInfo_init_zero           {"", "", 0, 0}
#define si_manage_AssetBeginRequest_init_zero    {"", 0, {0}}
#define si_manage_AssetBeginResponse_init_zero   {0, 0}
#define si_manage_JobSetRequest_init_zero        {{0}, _si_manage_Trigger_MIN}
#define si_manage_RunResult_init_zero            {0, _si_manage_Outcome_MIN, _si_manage_Stage_MIN, 0}
#define si_manage_JobStatus_init_zero            {0, "", {0}, _si_manage_Trigger_MIN, _si_manage_RunState_MIN, 0, false, si_manage_RunResult_init_zero}
#define si_manage_JobRunOnceResponse_init_zero   {0}
#define si_manage_JobCancelRequest_init_zero     {0}

/* Field tags (for use in manual encoding/decoding) */
#define si_manage_DeviceInfo_serial_tag          1
#define si_manage_DeviceInfo_firmware_version_tag 2
#define si_manage_DeviceInfo_storage_total_kb_tag 3
#define si_manage_DeviceInfo_storage_free_kb_tag 4
#define si_manage_AssetBeginRequest_name_tag     1
#define si_manage_AssetBeginRequest_size_tag     2
#define si_manage_AssetBeginRequest_sha256_tag   3
#define si_manage_AssetBeginResponse_present_tag 1
#define si_manage_AssetBeginResponse_offset_tag  2
#define si_manage_JobSetRequest_sha256_tag       1
#define si_manage_JobSetRequest_trigger_tag      2
#define si_manage_RunResult_run_id_tag           1
#define si_manage_RunResult_outcome_tag          2
#define si_manage_RunResult_failed_stage_tag     3
#define si_manage_RunResult_duration_ms_tag      4
#define si_manage_JobStatus_has_job_tag          1
#define si_manage_JobStatus_name_tag             2
#define si_manage_JobStatus_sha256_tag           3
#define si_manage_JobStatus_trigger_tag          4
#define si_manage_JobStatus_state_tag            5
#define si_manage_JobStatus_current_run_id_tag   6
#define si_manage_JobStatus_last_result_tag      7
#define si_manage_JobRunOnceResponse_run_id_tag  1
#define si_manage_JobCancelRequest_run_id_tag    1

/* Struct field encoding specification for nanopb */
#define si_manage_DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   serial,            1) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,   2) \
X(a, STATIC,   SINGULAR, UINT32,   storage_total_kb,   3) \
X(a, STATIC,   SINGULAR, UINT32,   storage_free_kb,   4)
#define si_manage_DeviceInfo_CALLBACK NULL
#define si_manage_DeviceInfo_DEFAULT NULL

#define si_manage_AssetBeginRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT32,   size,              2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, sha256,            3)
#define si_manage_AssetBeginRequest_CALLBACK NULL
#define si_manage_AssetBeginRequest_DEFAULT NULL

#define si_manage_AssetBeginResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     present,           1) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            2)
#define si_manage_AssetBeginResponse_CALLBACK NULL
#define si_manage_AssetBeginResponse_DEFAULT NULL

#define si_manage_JobSetRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, sha256,            1) \
X(a, STATIC,   SINGULAR, UENUM,    trigger,           2)
#define si_manage_JobSetRequest_CALLBACK NULL
#define si_manage_JobSetRequest_DEFAULT NULL

#define si_manage_RunResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   run_id,            1) \
X(a, STATIC,   SINGULAR, UENUM,    outcome,           2) \
X(a, STATIC,   SINGULAR, UENUM,    failed_stage,      3) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       4)
#define si_manage_RunResult_CALLBACK NULL
#define si_manage_RunResult_DEFAULT NULL

#define si_manage_JobStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_job,           1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, sha256,            3) \
X(a, STATIC,   SINGULAR, UENUM,    trigger,           4) \
X(a, STATIC,   SINGULAR, UENUM,    state,             5) \
X(a, STATIC,   SINGULAR, UINT32,   current_run_id,    6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  last_result,       7)
#define si_manage_JobStatus_CALLBACK NULL
#define si_manage_JobStatus_DEFAULT NULL
#define si_manage_JobStatus_last_result_MSGTYPE si_manage_RunResult

#define si_manage_JobRunOnceResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   run_id,            1)
#define si_manage_JobRunOnceResponse_CALLBACK NULL
#define si_manage_JobRunOnceResponse_DEFAULT NULL

#define si_manage_JobCancelRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   run_id,            1)
#define si_manage_JobCancelRequest_CALLBACK NULL
#define si_manage_JobCancelRequest_DEFAULT NULL

extern const pb_msgdesc_t si_manage_DeviceInfo_msg;
extern const pb_msgdesc_t si_manage_AssetBeginRequest_msg;
extern const pb_msgdesc_t si_manage_AssetBeginResponse_msg;
extern const pb_msgdesc_t si_manage_JobSetRequest_msg;
extern const pb_msgdesc_t si_manage_RunResult_msg;
extern const pb_msgdesc_t si_manage_JobStatus_msg;
extern const pb_msgdesc_t si_manage_JobRunOnceResponse_msg;
extern const pb_msgdesc_t si_manage_JobCancelRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define si_manage_DeviceInfo_fields &si_manage_DeviceInfo_msg
#define si_manage_AssetBeginRequest_fields &si_manage_AssetBeginRequest_msg
#define si_manage_AssetBeginResponse_fields &si_manage_AssetBeginResponse_msg
#define si_manage_JobSetRequest_fields &si_manage_JobSetRequest_msg
#define si_manage_RunResult_fields &si_manage_RunResult_msg
#define si_manage_JobStatus_fields &si_manage_JobStatus_msg
#define si_manage_JobRunOnceResponse_fields &si_manage_JobRunOnceResponse_msg
#define si_manage_JobCancelRequest_fields &si_manage_JobCancelRequest_msg

/* Maximum encoded size of messages (where known) */
#define SI_MANAGE_MANAGE_PB_H_MAX_SIZE           si_manage_JobStatus_size
#define si_manage_AssetBeginRequest_size         73
#define si_manage_AssetBeginResponse_size        8
#define si_manage_DeviceInfo_size                78
#define si_manage_JobCancelRequest_size          6
#define si_manage_JobRunOnceResponse_size        6
#define si_manage_JobSetRequest_size             36
#define si_manage_JobStatus_size                 97
#define si_manage_RunResult_size                 16

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
