/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.2 */

#include "manage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(si_manage_DeviceInfo, si_manage_DeviceInfo, AUTO)


PB_BIND(si_manage_SetTimeRequest, si_manage_SetTimeRequest, AUTO)


PB_BIND(si_manage_AssetBeginRequest, si_manage_AssetBeginRequest, AUTO)


PB_BIND(si_manage_AssetBeginResponse, si_manage_AssetBeginResponse, AUTO)


PB_BIND(si_manage_JobSetRequest, si_manage_JobSetRequest, AUTO)


PB_BIND(si_manage_RunResult, si_manage_RunResult, AUTO)


PB_BIND(si_manage_JobStatus, si_manage_JobStatus, AUTO)


PB_BIND(si_manage_JobRunOnceResponse, si_manage_JobRunOnceResponse, AUTO)


PB_BIND(si_manage_JobCancelRequest, si_manage_JobCancelRequest, AUTO)


PB_BIND(si_manage_BootRecord, si_manage_BootRecord, AUTO)


PB_BIND(si_manage_RunRecord, si_manage_RunRecord, AUTO)


PB_BIND(si_manage_LogReadRequest, si_manage_LogReadRequest, AUTO)


PB_BIND(si_manage_LogEntry, si_manage_LogEntry, AUTO)


PB_BIND(si_manage_LogReadResponse, si_manage_LogReadResponse, AUTO)


PB_BIND(si_manage_LogAckRequest, si_manage_LogAckRequest, AUTO)













